### PR TITLE
Add 2020

### PR DESCRIPTION
**Pull request by melMass**

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks for these @melMass, can you confirm this version is working? I suspect since Maya 2019 we need to update CentOS from 6 to 7. You can build and test it locally with these commands.

```bash
cd docker-maya
docker build -t mottosso/maya:2020 .
docker run -ti --rm mottosso/maya:2020
$ mayapy -c "print('I'm working just fine')"
```

**Comment by melMass** [comment]
Yes, thanks ! 
I'll test locally tonight or tomorrow (CET) and report back here.

**Comment by a772bNsz** [comment]
I've got CentOS7 with Maya dependencies setup on the my master branch if you guys want to check out. These are the warnings I get when I run docker, though:
```
This plugin does not support createPlatformOpenGLContext!
pymel.core : INFO : Updating pymel with pre-loaded plugins: cacheEvaluator, renderSetup
pymel.internal.startup : INFO : Skipping MEL initialization
```

**Comment by mottosso** [comment]
Thanks for that @a772bNsz! With the heavy lifting done, I went ahead and made an updated mayabase container.

- https://hub.docker.com/r/mottosso/mayabase-centos7

And then incorporated this PR into an updated maya:2020 container.

```bash
docker run --rm -ti mottosso/maya:2020
```

I'll see about getting [SP1](https://github.com/mottosso/docker-maya/pull/11) uploaded next, along with updating this repo with details.

- mottosso/mayabase-centos7 is 2 GB
- mottosso/maya:2020 adds another 4 GB

Enjoy!

**Comment by a772bNsz** [comment]
Happy to help, 2020sp1 works fine with the same /Packages inclusion to line 10

**Comment by mottosso** [comment]
2020 and 2020 SP1 have now been added. Thanks guys!

**Pull request closed without merging**
